server:
  port: 9999

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test1
          uri: lb://user-biz
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1